### ISSUE TITLE
Mixed model - can't seem to run model with random slopes (that will run in r)

### ISSUE THREAD

**Issue by scroono** [gamlj/gamlj#177]
Hi there - for teaching, I'm trying to run the sleep deprivation & reaction time analyses described here: https://statsnotebook.io/blog/analysis/linear_mixed_model/#sleep-deprivation-and-reaction-time-repeated-measures-design in the mixed models component of GAMLj (because both I and my students love it). Dataset attached. 

it runs for both random intercepts and for random intercepts & slopes in statsnotebook as described on the web page (using 
library(lme4)
library(lmerTest)

res <- lmer(Reaction ~ Days + (1 + Days | Subject),
  data = currentDataset)
summary(res)
confint(res, level = 0.95, method = "Wald")

it looks like I'm calling something similar in GAMLj

gamlj::gamljMixed(
    formula = Reaction ~ 0 + Days+( 1 + Days | Subject ),
    data = data,
    fixedIntercept = FALSE,
    plotRaw = TRUE,
    plotError = "ci",
    re_modelterms = FALSE,
    re_listing = "all",
    lrtRandomEffects = TRUE,
    plotRandomEffects = TRUE)

but I get the error "number of observations (=180) <= number of random effects (=180) for term (1+ Days | Subject); the random effects paramaters and the residual variance (or scale paramater) are probably unidentifiable"

While I love the error message saving us from doing something stupid, I always get that error (well, similar) whenever I have tried to fit a random slope in any dataset that I have used, and I've assumed this was a function of the data. Given that it runs in statsnotebook (also r) I'm now not so sure. 

Do you have any advice as to how to get this to run (or am I doing something stupid)? It would be great to use this for teaching. 

thanks for your time

[sleep.csv](https://github.com/gamlj/gamlj/files/10389785/sleep.csv)

**Comment by mcfanda** [comment]
Hi, it seems as the GAMLj error is due to the fact that the model does not have enough degrees of freedom. You have 10 days, that require 9 parameters to estimate the effect, plus one intercept, it make 10 parameters. Estimating the effect of days as random (so within each pearson) means estimating 10 parameters with 10 datapoints, so no DF left.

So it is correct that you get an error.

If you are able to estimate the model in some other software, it is likely because the other software does not consider "Days" as a factor but as continuous variable. If you transform "Days" into a numeric variable the model works also in GAMLj, but you need to check if this is what you want.

If you want to keep Days as a factor, you need to remove the random effect of Days from the random components

**Comment by mcfanda** [comment]
This is an example in jamovi with "Days" as continuous, which looks pretty nice (you need to unzip it because github does not allow to upload jamovi files)
[sleep.zip](https://github.com/gamlj/gamlj/files/10435133/sleep.zip)

**Comment by scroono** [comment]
oh! That is wonderful, thanks so much for sending the example through - it has made much clearer where I have been making an error and how to fix it. I *really* appreciate your help - thank you!
