### ISSUE TITLE
Question about the newest version for GAMLj3::gamlj_mixed argument

### ISSUE THREAD

**Issue by hiswy** [gamlj/gamlj#218]
Hello, I tried to use GAMLj3::gamlj_mixed function with AR1 argument but it appears 
it does not work. Below comment pops up on the console...

" unused argument (res_struct = "ar1") "

Is there any reason for it?

Thank you very much

**Comment by mcfanda** [comment]
Please reinstall it from github: it should work now

**Comment by hiswy** [comment]
If I may, [I'm not sure this is an appropriate place for this question],

when the autocorrelation is adjusted for the longitudinal analysis

Random Effect LFT does not show any result. I am sort of guessing this is a normal finding as the residuals structure for repeated meausures is set to autoregressive... Am I thinking right ?

Thank you for the response, again..
Sincerely yours...

**Comment by mcfanda** [comment]
I cannot  answer these questions without further information. Please send
an actual example as a .omv file so I can see what the actual problem is.
cheers
mc

Il Ven 22 Dic 2023, 23:36 Sang-Won Yoo ***@***.***> ha
scritto:

**Comment by hiswy** [comment]
I just uploaded the .omv file that I mentioned. 
[example.omv.zip](https://github.com/gamlj/gamlj/files/13757446/example.omv.zip)

**Comment by mcfanda** [comment]
Yes, that is expected behavior. LRT for random effects are not implemented when residual variance-covariance is not "Identity".

**Comment by mcfanda** [comment]
Since version 3.1.6 (coming out soon), you can make a model comparison to test random variance of the intercept when using autoregressive residual variance. This can be done activating "model comparison" and specifying a nested model with the same fixed effects as the original model but no random coefficients.
However, although this is now technically possible, it does not mean that the test is sensible. There's very scarce literature supporting this particular case, so it is up to the user to justify this test.
