### ISSUE TITLE
gamljmixed() simple effects not shown? 

### ISSUE THREAD

**Issue by Jeazh9** [gamlj/gamlj#238]
Hi, 

I am running a mixed model in Jamovi, and copy the syntax from Jamovi to R. Though the simple effect results were shown in Jamovi, the results arent shown in R resutls. There are the simple effect tables but the numbers are just not shown. 
<img width="665" alt="Screenshot 2024-04-12 at 9 49 04 PM" src="https://github.com/gamlj/gamlj/assets/166824517/e86f1ad8-6db3-48ea-99a1-77925b0fabd8">
 

This is my R codes: 
GAMLj3::gamljmixed(
    formula = P_SNAP_Inattentive_Avg ~ 1 + Timepoint + Group + Timepoint:Group + ( 1 | ParticipantCode ),
    data = VR1,
    plot_x = Timepoint,
    plot_z = Group,
    emmeans = ~ Timepoint + Group,
    simple_x = Timepoint,
    simple_mods = Group,
    simple_interactions = TRUE,
    norm_test = TRUE,
    res_struct='un') 

May I know what I may have done wrong? 
Thanks!

**Comment by mcfanda** [comment]
Hi
I cannot reproduce issue with standard data. If you get the results in jamovi but not in R is almost surely due to the variable set up. In jamovi, what you put in "Factors" is transformed into a categorical variable, what you put in "covariates" is coerced to a numeric variable. In R, if you pass the variables in a formula, their type is taken from the dataset (no coercion) . Thus, check if group is a factor (I guess it must be) and that the type of Timepoint is the one you intend. Check the results after setting the correct variable types.

**Comment by Jeazh9** [comment]
Hi, thank you for your prompt response. 
I double-checked the data - both Group and Timepoint are set as categorical variables in R, and the dv in the dataset is numeric. 
Anyhow, there are some covariates I put in the Jamovi interface, but it seems like the R codes aren't reflecting? 
Would it possibly be an issue for such errors occurred?

**Comment by Jeazh9** [comment]
Hihi, thanks for your prompt response. 
I just double checked, both Group and Timepoint are set as nominal variable and dv is a continuous one (same as they are in Jamovi). However, the simple effect tables are still empty in R results. 

Would there be any other solutions to fix the issues? Thanks!

**Comment by Jeazh9** [comment]
Hi, i changed the timepoint into a numeric variable and it works! thank you so much!
