### ISSUE TITLE
HELP: Show level-2 variances' p value when added random effect(s)!

### ISSUE THREAD

**Issue by ertugruluyar-github** [gamlj/gamlj#266]
Gamlj3 version is 3.3.6, jamovi via flatpak (version 2.5.9)
I am modeling two level HLM.
When I run null model, it is showing the p value of variance calculation in the "Random Effect LRT" table:
PV1MATH ~ 1 + ( 1 | CNTSCHID )
![image](https://github.com/user-attachments/assets/55108bc8-acc6-48dc-8b47-164f85d304b1)
But, when I run a model with random effect(s) it isn't:
PV1MATH ~ 1 + WORKPAY + ESCS + ( 1 + WORKPAY + ESCS | CNTSCHID )
![image](https://github.com/user-attachments/assets/bcd34fea-4a4d-4a82-8311-baa1000f0fbd)
But, if I add variable in the level-2 (fixed effect), it is showing:
PV1MATH ~ 1 + SC001Q01TA + SC013Q01TA + MEAN_ESCS + ( 1 | CNTSCHID )
![image](https://github.com/user-attachments/assets/0733ae4c-5ff9-4b93-b64e-626ba78e93a6)

Please help me, there is a problem or I am missing something in this regard.
Should I accept as p<.001 as in the null model?
Is there an option for to do show this?

**Comment by mcfanda** [comment]
Hi,
This is expected behavior. The reason is the following: in linear models, you always estimate all lower order effects, given the order of the model. For instance, if you have a variable effect (first order), you need the intercept (zero order) otherwise the interpretation of the variable effect changes (and not be what one expect). If you have an interaction a x b (second order), you need zero order (intercept) and the first order effects (effect of a and b) in the model.

For random effects, the logic is the same, so GAMLj3 tests the variances of the higher order effects. In fact, if you have (1 + x | cluster), you can not remove the intercept, so testing its variance has no meaning.

**Comment by ertugruluyar-github** [comment]
Thank you, but I can't get it because it is a complicated answer for me.
I am wondiring that "Is this p value in the 'Random Effect LRT' table is the same thing in the HLM 8 software's 'Final estimation of variance components' table?"
![image](https://github.com/user-attachments/assets/b4453d1f-e563-47f7-b2b0-d77e1e095209)

**Comment by mcfanda** [comment]
Hi, I am afraid I am not familiar with HLM software. Nonetheless, it looks like  it's doing the same thing. Practically, the p-values of the random variances are the ones you find in the "Random Effect LRT".

**Comment by ertugruluyar-github** [comment]
@mcfanda Thank you, I really appreciated, have a nice day.

**Comment by mcfanda** [comment]
I am afraid there has been a misunderstanding. In HLM models and thus in mixed models, there is no " level-2 variance". There are variances of random coefficients that vary across level-2 levels (the clustering variable). Thus, in a model with only the intercept as random coefficient, you get the inferential test for the intercept variance. In a model with intercept and slope random coefficients, you get the inferential test only of the slope variance because in that model, removing the intercept will change the variance of the slope (making it meaningless). 

As regards variance explained, there is no consensus on how to compute it. However, if you want to estimate how much variance your random coefficients explain over and beyond the random intercept, you can use model comparison (it is an option in the module), and compare the "R-squared  conditional" of a model with only random intercepts with a model with random intercept and random slopes. GAMLj3 gives the difference ("Delta R-squared") and the tests in the table "Model Fit".

This is doable in GAMLj3. It is not implemented "automatically", so it cannot become a feature,  because its correct computation depends on the specific model, so the user should do it with models comparison.

**Comment by mcfanda** [comment]
here the help for model comparison https://gamlj.github.io/mixed.html#models-comparison

**Comment by ertugruluyar-github** [comment]
I am really appreciate for your answers and pation. 
I have asked Claude AI two question and "Modef Fit" table that you give me on this link.
![Uploading image.png…]()

**Comment by mcfanda** [comment]
You Claude AI answers are correct. I guess you have all information you need. I am sorry but I cannot suggest you what to report in your thesis. That would be beyond the scope of this page, which is  about the software.

**Comment by ertugruluyar-github** [comment]
Thank you again and again, I am closing this issue.
